### ISSUE TITLE
cant' search images

### ISSUE THREAD

**Issue by David-9527** [ishare2-org/ishare2-cli#13]
root@pnetlab:~# ishare2 search all

QEMU available images list

To pull an image, use the following command: ishare2 pull qemu <number>

DYNAMIPS available images list

To pull an image, use the following command: ishare2 pull dynamips <number>

BIN available images list

To pull an image, use the following command: ishare2 pull bin <number>
 
root@pnetlab:~#

**Comment by sudoalx** [comment]
update ishare2 to the latest version
