### ISSUE TITLE
cannot download or see the list

### ISSUE THREAD

**Issue by StudentCyberOps** [ishare2-org/ishare2-cli#15]
root@pnetlab:~# ping google.com
PING google.com (172.217.19.46) 56(84) bytes of data.
64 bytes from mrs08s03-in-f14.1e100.net (172.217.19.46): icmp_seq=1 ttl=128 time=35.0 ms
64 bytes from mrs08s03-in-f14.1e100.net (172.217.19.46): icmp_seq=2 ttl=128 time=41.1 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 35.054/38.086/41.119/3.038 ms

root@pnetlab:~# ishare2 search all
**[!] Running connection test to check your internet connection.**
[-] Running connection tests... 
[-] Checking if GitHub is reachable... 
[+] GitHub is reachable. 
[-] Checking if LabHub (Google Drive backend) is reachable... 
[+] LabHub (Google Drive backend) is reachable. 
[-] Checking if Google DNS is reachable... 
[+] Google DNS is reachable. 
[-] Checking if LabHub (Onedrive backend) is reachable... 
[+] LabHub (Onedrive backend) is reachable. 
[-] Checking if GitHub Raw Files is reachable... 
[+] GitHub Raw Files is reachable. 
[-] Connection tests completed. 

root@pnetlab:~# 

![Uploading Screenshot 2024-10-26 at 5.02.36 PM.png…]()

**Comment by sudoalx** [comment]
You're using a very old version of ishare2. Please refer to the documentation to install the latest version.

**Comment by sudoalx** [comment]
Try this and then run ishare2 again after that:
```bash
rm /opt/ishare2/
```
 Make sure you're using the latest version of ishare2

**Comment by ru4chmchp** [comment]
root@pnetlab:~# ishare2 gui start
Failed to start ishare2_gui.service: Unit ishare2_gui.service not found.
[-] Error starting ishare2 GUI service. 
[-] Please see the logs for troubleshooting. Run: systemctl status ishare2_gui.service
