### ISSUE TITLE
How to release the online mode owner without the owner password? 

### ISSUE THREAD

**Issue by LesenHuang** [ishare2-org/ishare2-cli#2]
After installing and upgrading pnetlab v6 through ishare2, I found that the owner in online mode is not free box but jsilva. How should I release the owner jsilva? I don't have his password.

<img width="498" alt="system online mode on" src="https://github.com/pnetlabrepo/ishare2/assets/119478008/092be879-30e8-4e2e-9adc-d1e50d23fc84">
<img width="523" alt="system online mode off" src="https://github.com/pnetlabrepo/ishare2/assets/119478008/5e5aad03-861a-4b93-9c1c-537fa06542b9">

If this problem cannot be solved, my pnetlab box will not be able to log in to its own online users.

<img width="1103" alt="pnetlab online login interface" src="https://github.com/pnetlabrepo/ishare2/assets/119478008/967e63ba-1ee8-42b6-a3d4-efc18ea0d9a8">

**Comment by sudoalx** [comment]
Hello, please contact PNetLab support for PNetLab related problems as we are a separate team and this repo must remain for ishare2 related problems only.
