### ISSUE TITLE
Installing ishare2 dependencies... ERROR https://repo.pnetlab.com ./ Packages - Certificate verification failed

### ISSUE THREAD

**Issue by nikclos** [ishare2-org/ishare2-cli#4]
root@pnetlab:~# wget -O /usr/sbin/ishare2 https://raw.githubusercontent.com/ishare2-org/ishare2-cli/main/ishare2 && chmod +x /usr/sbin/ishare2 && ishare2
--2023-12-25 08:55:55--  https://raw.githubusercontent.com/ishare2-org/ishare2-cli/main/ishare2
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65034 (64K) [text/plain]
Saving to: ‘/usr/sbin/ishare2’

/usr/sbin/ishare2                                                              100%[====================================================================================================================================================================================================>]  63.51K  --.-KB/s    in 0.03s   

2023-12-25 08:55:55 (1.81 MB/s) - ‘/usr/sbin/ishare2’ saved [65034/65034]

 [*] Installing ishare2 dependencies...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.58.0-2ubuntu3.24).
The following packages were automatically installed and are no longer required:
  libnetplan0 python3-netifaces
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 380 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wget is already the newest version (1.19.4-1ubuntu2.2).
The following packages were automatically installed and are no longer required:
  libnetplan0 python3-netifaces
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 380 not upgraded.
 [+] jq is not installed.
 [+] Updating package lists...
Hit:1 http://vn.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://vn.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://vn.archive.ubuntu.com/ubuntu bionic-backports InRelease                               
Hit:5 http://vn.archive.ubuntu.com/ubuntu bionic-security InRelease      
Ign:4 https://repo.pnetlab.com ./ InRelease      
Ign:6 https://repo.pnetlab.com ./ Release        
Ign:7 https://repo.pnetlab.com ./ Packages        
Ign:8 https://repo.pnetlab.com ./ Translation-en   
Ign:7 https://repo.pnetlab.com ./ Packages         
Ign:8 https://repo.pnetlab.com ./ Translation-en  
Ign:7 https://repo.pnetlab.com ./ Packages        
Ign:8 https://repo.pnetlab.com ./ Translation-en  
Ign:7 https://repo.pnetlab.com ./ Packages         
Ign:8 https://repo.pnetlab.com ./ Translation-en   
Ign:7 https://repo.pnetlab.com ./ Packages         
Ign:8 https://repo.pnetlab.com ./ Translation-en  
Ign:7 https://repo.pnetlab.com ./ Packages        
Ign:8 https://repo.pnetlab.com ./ Translation-en   
Err:7 https://repo.pnetlab.com ./ Packages         
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 14.225.16.78 443]
Ign:8 https://repo.pnetlab.com ./ Translation-en  
Reading package lists... Done
E: Failed to fetch https://repo.pnetlab.com/./Packages  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 14.225.16.78 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
 [-] Failed to update package lists.

**Comment by chaiguifeng007** [comment]
try：“apt install ca-certificates”

**Comment by nikclos** [comment]
This  not working 4 me
I`m try:
sudo rm /etc/resolv.conf
sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf

sudo apt-get install -y ca-certificates
sudo dpkg-reconfigure ca-certificates
sudo update-ca-certificates

Then:
Installing ishare2 dependencies...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.58.0-2ubuntu3.24).
The following packages were automatically installed and are no longer required:
  libnetplan0 python3-netifaces
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 379 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wget is already the newest version (1.19.4-1ubuntu2.2).
The following packages were automatically installed and are no longer required:
  libnetplan0 python3-netifaces
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 379 not upgraded.
 [+] jq is not installed.
 [+] Updating package lists...
Hit:1 http://vn.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://vn.archive.ubuntu.com/ubuntu bionic-updates InRelease                                
Hit:3 http://vn.archive.ubuntu.com/ubuntu bionic-backports InRelease                               
Hit:5 http://vn.archive.ubuntu.com/ubuntu bionic-security InRelease      
Ign:4 https://repo.pnetlab.com ./ InRelease       
Ign:6 https://repo.pnetlab.com ./ Release        
Ign:7 http://repo.pnetlab.com ./ Packages
Ign:7 https://repo.pnetlab.com ./ Packages
Ign:8 http://repo.pnetlab.com ./ Translation-en
Ign:8 https://repo.pnetlab.com ./ Translation-en
Ign:7 http://repo.pnetlab.com ./ Packages
Ign:7 https://repo.pnetlab.com ./ Packages
Ign:8 http://repo.pnetlab.com ./ Translation-en
Ign:8 https://repo.pnetlab.com ./ Translation-en
Ign:7 http://repo.pnetlab.com ./ Packages
Ign:7 https://repo.pnetlab.com ./ Packages
Ign:8 http://repo.pnetlab.com ./ Translation-en
Ign:8 https://repo.pnetlab.com ./ Translation-en
Get:7 https://repo.pnetlab.com ./ Packages [4899 B]
Ign:8 http://repo.pnetlab.com ./ Translation-en  
Ign:8 https://repo.pnetlab.com ./ Translation-en
Ign:8 http://repo.pnetlab.com ./ Translation-en
Ign:8 https://repo.pnetlab.com ./ Translation-en
Ign:8 http://repo.pnetlab.com ./ Translation-en                                                                                                                                                                                                                                                                            
Ign:8 https://repo.pnetlab.com ./ Translation-en                                                                                                                                                                                                                                                                           
Ign:8 http://repo.pnetlab.com ./ Translation-en                                                                                                                                                                                                                                                                            
Ign:8 https://repo.pnetlab.com ./ Translation-en                                                                                                                                                                                                                                                                           
Fetched 4899 B in 7s (697 B/s)                                                                                                                                                                                                                                                                                             
Reading package lists... Done
E: Failed to fetch http://repo.pnetlab.com/./en  404  Not Found [IP: 14.225.16.78 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
 [-] Failed to update package lists.
root@pnetlab:~# ping 14.225.16.78 443
PING 443 (0.0.1.187) 56(124) bytes of data.
64 bytes from 14.225.16.78: icmp_seq=1 ttl=128 time=213 ms
64 bytes from 14.225.16.78: icmp_seq=2 ttl=128 time=211 ms

Most likely, the issue is indeed the absence of packages in the pnetlab repository.

**Comment by chaiguifeng007** [comment]
now ,we have the same err……

**Comment by HAlover99** [comment]
same issue

**Comment by sudoalx** [comment]
1. Open sources.list with a text editor like nano.
nano /etc/apt/sources.list

2. Remove or comment out the line with repo.pnetlab.com as source:
- Locate the line starting with "deb [trusted=yes] https://repo.pnetlab.com ./"
Prepend "#" before that line, resulting in:
# deb [trusted=yes] https://repo.pnetlab.com ./

3. Paste this mirror at the bottom of the file:
deb [trusted=yes] https://pnetlab.labhub.eu.org ./

This is mostly useful on fresh installs but can also solve the error mentioned in the previous message.
Let's hope my server can keep up with the requests 😆

- [How to use nano](https://linuxize.com/post/how-to-use-nano-text-editor/)
