### ISSUE TITLE
Failed to fetch http://repo.pnetlab.com/./en_US  404  Not Found [IP: 14.225.16.78 443]

### ISSUE THREAD

**Issue by chaiguifeng007** [ishare2-org/ishare2-cli#5]
Reading package lists... Done
E: Failed to fetch http://repo.pnetlab.com/./en_US  404  Not Found [IP: 14.225.16.78 443]
E: Failed to fetch http://repo.pnetlab.com/./en  404  Not Found [IP: 14.225.16.78 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
 [-] Failed to update package lists.

**Comment by HAlover99** [comment]
same issue

**Comment by sudoalx** [comment]
1. Open sources.list with a text editor like nano.
nano /etc/apt/sources.list

2. Remove or comment out the line with repo.pnetlab.com as source:
- Locate the line starting with "deb [trusted=yes] https://repo.pnetlab.com ./"
Prepend "#" before that line, resulting in:
```bash
# deb [trusted=yes] https://repo.pnetlab.com ./
```

3. Paste this mirror at the bottom of the file:
deb [trusted=yes] https://pnetlab.labhub.eu.org ./

This is mostly useful on fresh installs but can also solve the error mentioned in the previous message.
Let's hope my server can keep up with the requests 😆

- [How to use nano](https://linuxize.com/post/how-to-use-nano-text-editor/)

**Comment by abing16** [comment]
Err:1 https://pnetlab.labhub.eu.org ./ pnetlab-qemu 4.0.0
  File has unexpected size (113255950 != 114413556). Mirror sync in progress? [IP: 104.21.48.1 443]
  Hashes of expected file:
   - SHA256:2bdaed26b4ba3eb107939ba9f7a1f286641ce0c3e1328727e98489c8c4f605fb
   - SHA1:fe326eeeff82a521a1c1532521b737ebea6dfc9e [weak]
   - MD5Sum:3a2ed661dbd6193dd09affe7e91c355f [weak]
   - Filesize:114413556 [weak]
E: Failed to fetch https://pnetlab.labhub.eu.org/./pool/pnetlab-qemu/pnetlab-qemu-4.0.0.deb  File has unexpected size (113255950 != 114413556). Mirror sync in progress? [IP: 104.21.48.1 443]
   Hashes of expected file:
    - SHA256:2bdaed26b4ba3eb107939ba9f7a1f286641ce0c3e1328727e98489c8c4f605fb
    - SHA1:fe326eeeff82a521a1c1532521b737ebea6dfc9e [weak]
    - MD5Sum:3a2ed661dbd6193dd09affe7e91c355f [weak]
    - Filesize:114413556 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by sudoalx** [comment]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> 
> 
> 

Did you try running apt update?
Else you can try using repo.pnetlab.com with https://
It's also worth checking you can visit the sites from a web browser just to double check there's no firewall rules blocking it
