### ISSUE TITLE
GPG error: http://i-share.top/repo

### ISSUE THREAD

**Issue by Cadavezz** [ishare2-org/ishare2-cli#6]
I'm receiving the following error:

```
Reading package lists... Done
E: GPG error: http://i-share.top/repo ./ Release: Signed file isn't valid, got 'NODATA' (does the network require authentication?)
 [-] Failed to update package lists.
```
Upon accessing [http://i-share.top/repo](http://i-share.top/repo) I verify that the domain is for sale.

**Comment by sudoalx** [comment]
ishare != ishare2
If you are facing this error when trying to install a package through APT, it means your apt package manager configuration is broken.

ishare.top is the domain name that was used by the now dead ishare tool. To fix this error, delete it from the sources.list file.
Through the CLI run:
nano /etc/apt/sources.list

Once you have entered the editor, remove the ishare.top line from the list.

[Check how to use nano](https://www.nano-editor.org/dist/latest/cheatsheet.html)
(Navigate with arrow keys. CTRL+s to save changes, CTRL+x to exit)
