### ISSUE TITLE
Cant get gui to work

### ISSUE THREAD

**Issue by Myztic90** [ishare2-org/ishare2-cli#7]
Tried clean install of pnetlab and ishare2cli

when I do ishare2 gui start or upgrade or install I get this error.

root@pnetlab:~# ishare2 gui start
Failed to start ishare2_gui.service: Unit ishare2_gui.service not found.
 [-] Error starting ishare2 GUI service.
 [-] Please see the logs for troubleshooting. Run: systemctl status ishare2_gui.service

I've tried both OVA file from pnetlab and clean install with ubuntu ubuntu-20.04.6-live-server-amd64 installing ishare and pnetlab v6 there.

Always have issue with ishare2. I used to have a working ishare2 before it was ishare2cli.

if i use only ishare2 pull/search it will work just not the gui part.

**Comment by sudoalx** [comment]
A fix is under development. The current version won't be fixed.
