### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by lemowa** [ishare2-org/ishare2-cli#8]
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
[-] Failed to update package lists.
[!] Attempting to fix APT sources...
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
[-] Failed to fix APT sources.

Can you helpme for this ?

**Comment by sudoalx** [comment]
You must fix issues with the APT package manager. This is not an issue related to ishare2 it's because of your Ubuntu installation. You can find help regarding this problem here:
https://askubuntu.com/questions/335794/could-not-get-lock-var-lib-apt-lists-lock
