### ISSUE TITLE
Ishare2 GUI notworking

### ISSUE THREAD

**Issue by AkaUdeptrai** [ishare2-org/ishare2-cli#9]
Hello everyone, 
I have installed Ishare2 GUI many times, but today I can't install Ishare2 GUI anymore,

root@pnetlab:/opt/unetlab/addons/qemu# isare2 upgrade
1) Upgrade ishare2
2) Upgrade PNETLab
3) Upgrade isshare2 GUI
4) Exit
Please, choose an option: 3
  [+] isare2 GUI is being downloaded and installed. Please, wait until the process is done...
  [!] Stopping isare2 GUI service...

  [-] isare2 GUI installation was canceled.
root@pnetlab:/opt/unetlab/addons/qemu# ishare2 gui install
  [+] isare2 GUI is being downloaded and installed. Please, wait until the process is done...
  [!] Stopping isare2 GUI service...

  [-] isare2 GUI installation was canceled.

ishare2: 3.3.5-main Up to date
ishare2 Channel: main
PNETLab v6.0.0-100 is installed.
OS: Ubuntu 20.04

**Comment by sudoalx** [comment]
As you can read in the documentation: https://github.com/ishare2-org/ishare2-web-gui this will only work on Ubuntu 20.04
